### ISSUE TITLE
oauth-resource-server - cannot find module 'passport-okta-oidc-bearer'

### ISSUE THREAD

**Issue by bhanchand** [jmelberg/oauth-resource-server#1]
node server.js 
module.js:491
    throw err;
    ^

Error: Cannot find module 'passport-okta-oidc-bearer'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/bhapr09/Documents/AndroidOAuth/gravatar/oauth-resource-server-master/server.js:25:16)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

**Comment by jmelberg-okta** [comment]
Hi @bhanchand. This repo is no longer actively maintained, but I was able to track down the issue you are seeing.

The dependency has been renamed to `passport-oauth2-jwt-bearer`. Simply update the `package.json` to use the new dependency name:

```json
{
  "name": "oauth-api",
  ...
  "dependencies": {
   ...
    "passport-oauth2-jwt-bearer": "https://github.com/mcguinness/passport-okta-oidc-bearer.git"
  }
}
```
